<a href="https://colab.research.google.com/github/Murugavl/PYTHON-PROGRAMS/blob/main/Linear_Algebra_Using_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import numpy as np
import scipy.linalg as linalg

print(" \n The quadratic equations are 3x+4y=10 and 2x+5y=9")
a=np.array([[3,4],[2,5]]) # we represent the coefficient values of x and y in one array
b=np.array([10,9])  # we represent the solution values in the another array
# to calculate the value of x and y values
print("\n The Values of X and Y are: ",linalg.solve(a,b))

#to find the determinent fo the matrix
a1=np.array([[1,2,3],[4,0,6],[7,8,9]])
print("\n The Matrix is : \n",a1)
print("\n The Determinent of the Matrix is : ",linalg.det(a1))

#to find the inverse of the matrix
print("\n The inverse of the Matrix is : \n",linalg.inv(a1))

#to find eigen value and eigen vector
a=np.array([[1, 1,0], [1, 2,1],[0,1,1]])
print("\n The Matrix Elements are: \n",a)
eigen_value, eigen_vector=linalg.eig(a)
print("\n Eigen Values are : ",eigen_value)
print("\n Eigen Vectors are : \n",eigen_vector)
#to find singular value decomposition
p=eigen_vector
pinverse=np.linalg.inv(eigen_vector)
print("\n Inverse of Eigen vectors: \n",linalg.inv(eigen_vector))
d=[]
for index, egvalue in enumerate (eigen_value) :
      row=np.zeros((3,))
      row[index]=egvalue
      d.append(row)
d=np.array(d)
print("\n The Singular Decomposition is \n",p@d@pinverse)

 
 The quadratic equations are 3x+4y=10 and 2x+5y=9

 The Values of X and Y are:  [2. 1.]

 The Matrix is : 
 [[1 2 3]
 [4 0 6]
 [7 8 9]]

 The Determinent of the Matrix is :  60.0

 The inverse of the Matrix is : 
 [[-0.8         0.1         0.2       ]
 [ 0.1        -0.2         0.1       ]
 [ 0.53333333  0.1        -0.13333333]]

 The Matrix Elements are: 
 [[1 1 0]
 [1 2 1]
 [0 1 1]]

 Eigen Values are :  [ 3.00000000e+00+0.j  1.00000000e+00+0.j -3.36770206e-17+0.j]

 Eigen Vectors are : 
 [[-4.08248290e-01  7.07106781e-01  5.77350269e-01]
 [-8.16496581e-01  2.61239546e-16 -5.77350269e-01]
 [-4.08248290e-01 -7.07106781e-01  5.77350269e-01]]

 Inverse of Eigen vectors: 
 [[-4.08248290e-01 -8.16496581e-01 -4.08248290e-01]
 [ 7.07106781e-01  2.77555756e-16 -7.07106781e-01]
 [ 5.77350269e-01 -5.77350269e-01  5.77350269e-01]]

 The Singular Decomposition is 
 [[ 1.00000000e+00  1.00000000e+00 -2.01275528e-17]
 [ 1.00000000e+00  2.00000000e+00  1.00000000e+00]
 [-7.95837601e-17  1.000000

<ipython-input-11-5fae4dbfc869>:31: ComplexWarning: Casting complex values to real discards the imaginary part
  row[index]=egvalue
